# List the start up tasks. Learn more https://www.gitpod.io/docs/config-start-tasks/
tasks:
  - before: |
      cd public/datastack
      npm install -g @angular/cli
    init: npm install       
    command: ng serve --disable-host-check

  - before:  |
      cd datastack
      pip install -r requirement.txt
    command: python api/app.py


# List the ports to expose. Learn more https://www.gitpod.io/docs/config-ports/
ports:
  - port: 3000
    onOpen: open-preview
